// Archivo: DataRepository.kt
package com.example.proyectofinal261e02

// Las 25 preguntas codificadas que se usarán en el examen.
val FullQuestionBank: List<Question> = listOf(

    // Módulo 1: Saludos y TO BE
    Question(id_pregunta = 1, enunciado = "I ___ happy.", opciones = listOf("are", "is", "am", "be"), respuesta_correcta = "am"),
    Question(id_pregunta = 2, enunciado = "Traduce \"Ella está bien\".", opciones = listOf("He is fine", "She is fine", "You are well", "I am fine"), respuesta_correcta = "She is fine"),
    Question(id_pregunta = 3, enunciado = "We ___ friends.", opciones = listOf("am", "is", "are", "be"), respuesta_correcta = "are"),
    // Módulo 2: Números y Artículos
    Question(id_pregunta = 4, enunciado = "¿Como se dice \"Rojo\" en ingles?", opciones = listOf("Green", "Yellow", "Blue", "Red"), respuesta_correcta = "Red"),
    Question(id_pregunta = 5, enunciado = "That is ___ orange.", opciones = listOf("a", "an", "some", "the"), respuesta_correcta = "an"),
    Question(id_pregunta = 6, enunciado = "El plural de \"Cat\" es:", opciones = listOf("Cats", "Catts", "Catties", "Cates"), respuesta_correcta = "Cats"),
    // Módulo 3: Familia y Posesivos
    Question(id_pregunta = 7, enunciado = "This is ___ (de el) car.", opciones = listOf("My", "Her", "His", "Your"), respuesta_correcta = "His"),
    Question(id_pregunta = 8, enunciado = "Traduce \"Mi hermana\".", opciones = listOf("His sister", "My brother", "My sister", "Your mother"), respuesta_correcta = "My sister"),
    // Módulo 4: Descripciones Físicas
    Question(id_pregunta = 9, enunciado = "¿Como se dice \"Alto\" (de estatura)?", opciones = listOf("Small", "Thin", "Short", "Tall"), respuesta_correcta = "Tall"),
    Question(id_pregunta = 10, enunciado = "Traduce \"Ella no es vieja\".", opciones = listOf("He is not old", "She is not young", "She is not old", "It is not old"), respuesta_correcta = "She is not old"),
    // Módulo 5: Verbos de Acción
    Question(id_pregunta = 11, enunciado = "I ___ coffee every morning.", opciones = listOf("drinks", "drink", "is drinking", "drunk"), respuesta_correcta = "drink"),
    Question(id_pregunta = 12, enunciado = "Traduce \"Ellos viven en Mexico\".", opciones = listOf("They lives in Mexico", "They live in Mexico", "We live in Mexico", "He lives in Mexico"), respuesta_correcta = "They live in Mexico"),
    Question(id_pregunta = 13, enunciado = "Traduce \"Nosotros hablamos ingles\".", opciones = listOf("We speaks English", "We speak Spanish", "We speak English", "You speak English"), respuesta_correcta = "We speak English"),
    // Módulo 6: Rutinas
    Question(id_pregunta = 14, enunciado = "She ___ up at 7 AM.", opciones = listOf("wake", "wakes", "waking", "is wake"), respuesta_correcta = "wakes"),
    Question(id_pregunta = 15, enunciado = "Traduce \"El ve television\".", opciones = listOf("She watches TV", "He watch TV", "He watches TV", "They watch TV"), respuesta_correcta = "He watches TV"),
    // Módulo 7: Preposiciones
    Question(id_pregunta = 16, enunciado = "The book is ___ the table.", opciones = listOf("under", "in", "on", "next"), respuesta_correcta = "on"),
    Question(id_pregunta = 17, enunciado = "Traduce \"El gato esta en la caja\".", opciones = listOf("The cat is on the box", "The cat is under the box", "The cat is in the box", "The box is in the cat"), respuesta_correcta = "The cat is in the box"),
    // Módulo 8: CAN (Habilidad)
    Question(id_pregunta = 18, enunciado = "Traduce \"El no puede correr\".", opciones = listOf("He don't run", "He can't run", "He isn't run", "He can runs"), respuesta_correcta = "He can't run"),
    Question(id_pregunta = 19, enunciado = "___ you drive a car?.", opciones = listOf("Are", "Is", "Do", "Can"), respuesta_correcta = "Can"),
    // Módulo 9: Contables/Incontables
    Question(id_pregunta = 20, enunciado = "I have ___ apples (afirmativo).", opciones = listOf("any", "some", "a", "an"), respuesta_correcta = "some"),
    Question(id_pregunta = 21, enunciado = "We don't have ___ milk (negativo).", opciones = listOf("some", "an", "a", "any"), respuesta_correcta = "any"),
    // Módulo 10: Repaso
    Question(id_pregunta = 22, enunciado = "They ___ watching TV now.", opciones = listOf("is", "are", "am", "do"), respuesta_correcta = "are"),
    Question(id_pregunta = 23, enunciado = "The cat is ___ the box (encima).", opciones = listOf("in", "under", "on", "next to"), respuesta_correcta = "on"),
    Question(id_pregunta = 24, enunciado = "We ___ eat breakfast at 8 AM.", opciones = listOf("doesn't", "don't", "isn't", "aren't"), respuesta_correcta = "don't"),
    Question(id_pregunta = 25, enunciado = "Traduce \"Somos estudiantes\".", opciones = listOf("You are students", "We are teachers", "We are students", "They are students"), respuesta_correcta = "We are students"),
    Question(id_pregunta = 26, enunciado = "¿Cómo se dice \"Hola\" en inglés?", opciones = listOf("Good", "Bye", "Hello", "Thanks"), respuesta_correcta = "Hello"),
    Question(id_pregunta = 27, enunciado = "Selecciona el saludo de la tarde.", opciones = listOf("Good night", "Good morning", "Good afternoon", "Goodbye"), respuesta_correcta = "Good afternoon"),
    Question(id_pregunta = 28, enunciado = "¿Como se dice \"¿Mi nombre es...?\"?", opciones = listOf("I am name", "My name is", "Name is my", "I name is"), respuesta_correcta = "My name is"),
    Question(id_pregunta = 29, enunciado = "We ___ friends.", opciones = listOf("am", "is", "are", "be"), respuesta_correcta = "are"),
    Question(id_pregunta = 30, enunciado = "Traduce \"Tu eres genial.\"", opciones = listOf("I am cool", "You is cool", "You are great", "He is great"), respuesta_correcta = "You are great"),
    Question(id_pregunta = 31, enunciado = "They ___ at home.", opciones = listOf("is", "am", "are", "were"), respuesta_correcta = "are"),
    Question(id_pregunta = 32, enunciado = "La respuesta a ¿How are you? suele ser:", opciones = listOf("Good night", "I am fine", "My name is", "He is sad"), respuesta_correcta = "I am fine"),
    Question(id_pregunta = 33, enunciado = "Selecciona el numero 7.", opciones = listOf("five", "three", "seven", "ten"), respuesta_correcta = "seven"),
    Question(id_pregunta = 34, enunciado = "This is ___ book.", opciones = listOf("an", "a", "the", "some"), respuesta_correcta = "a"),
    Question(id_pregunta = 35, enunciado = "Traduce \"Nueve y Dos\"", opciones = listOf("Three and ten", "Nine and two", "Seven and five", "One and eight"), respuesta_correcta = "Nine and two"),
    Question(id_pregunta = 36, enunciado = "¿Que color es Yellow?", opciones = listOf("Azul", "Verde", "Amarillo", "Blanco"), respuesta_correcta = "Amarillo"),
    Question(id_pregunta = 37, enunciado = "¿Que numero es Four?", opciones = listOf("1", "4", "8", "2"), respuesta_correcta = "4"),
    Question(id_pregunta = 38, enunciado = "Traduce \"Una escuela\"", opciones = listOf("An school", "The school", "A school", "Some school"), respuesta_correcta = "A school"),
    Question(id_pregunta = 39, enunciado = "I have ___ umbrella.", opciones = listOf("a", "an", "the", "this"), respuesta_correcta = "an"),
    Question(id_pregunta = 40, enunciado = "¿Cómo se dice Madre?", opciones = listOf("Father", "Sister", "Mother", "Brother"), respuesta_correcta = "Mother"),
    Question(id_pregunta = 41, enunciado = "She is ___ (de ella) teacher.", opciones = listOf("My", "His", "Her", "Their"), respuesta_correcta = "Her"),
    Question(id_pregunta = 42, enunciado = "¿Cómo se dice Abuelo?", opciones = listOf("Grandparent", "Grandmother", "Grandfather", "Son"), respuesta_correcta = "Grandfather"),
    Question(id_pregunta = 43, enunciado = "We are ___  (nuestros) parents.", opciones = listOf("Our", "Your", "My", "Her"), respuesta_correcta = "Our"),
    Question(id_pregunta = 44, enunciado = "I love ___ family.", opciones = listOf("Your", "My", "Her", "Their"), respuesta_correcta = "My"),
    Question(id_pregunta = 45, enunciado = "¿Que significa \"Daughter\"?", opciones = listOf("Hijo", "Hermana", "Padre", "Hija"), respuesta_correcta = "Hija"),
    Question(id_pregunta = 46, enunciado = "Traduce \"Su (de usted) casa\".", opciones = listOf("My house", "Their house", "Your house", "His house"), respuesta_correcta = "Your house"),
    Question(id_pregunta = 47, enunciado = "___ (de ellos) dog is big.", opciones = listOf("Our", "Your", "Their", "My"), respuesta_correcta = "Their"),
    Question(id_pregunta = 48, enunciado = "I ___ not a doctor.", opciones = listOf("are", "is", "am", "be"), respuesta_correcta = "am"),
    Question(id_pregunta = 49, enunciado = "She ___ beautiful.", opciones = listOf("are not", "is not", "am not", "were not"), respuesta_correcta = "is not"),
    Question(id_pregunta = 50, enunciado = "El opuesto de \"Big\" es:", opciones = listOf("Fat", "Tall", "Small", "New"), respuesta_correcta = "Small"),
    Question(id_pregunta = 51, enunciado = "They ___ tired.", opciones = listOf("is not", "am not", "are not", "isn´t"), respuesta_correcta = "are not"),
    Question(id_pregunta = 52, enunciado = "¿Como se dice \"Guapo\"?", opciones = listOf("Ugly", "Cute", "Good", "Handsome"), respuesta_correcta = "Handsome"),
    Question(id_pregunta = 53, enunciado = "Contraccion de is not:", opciones = listOf("are´nt", "amn´t", "isn´t", "aren´t"), respuesta_correcta = "isn´t"),
    Question(id_pregunta = 54, enunciado = "We ___ from Spain.", opciones = listOf("is not", "am not", "aren´t", "doesn´t"), respuesta_correcta = "aren´t"),
    Question(id_pregunta = 55, enunciado = "¿Que significa \"Thin\"?", opciones = listOf("Gordo", "Fuerte", "Delgado", "Alto"), respuesta_correcta = "Delgado"),
    Question(id_pregunta = 56, enunciado = "¿Cómo se dice \"Comer\"?", opciones = listOf("Sleep", "Drink", "Eat", "Read"), respuesta_correcta = "Eat"),
    Question(id_pregunta = 57, enunciado = "I ___ coffee every morning.", opciones = listOf("drinks", "drink", "is drinking", "drunk"), respuesta_correcta = "drink"),
    Question(id_pregunta = 58, enunciado = "We ___ to the park.", opciones = listOf("goes", "go", "is going", "went"), respuesta_correcta = "go"),
    Question(id_pregunta = 59, enunciado = "¿Cómo se dice \"Trabajar\"?", opciones = listOf("Play", "Work", "Study", "See"), respuesta_correcta = "Work"),
    Question(id_pregunta = 60, enunciado = "You ___ a lot of books.", opciones = listOf("reads", "read", "reading", "are read"), respuesta_correcta = "read"),
    Question(id_pregunta = 61, enunciado = "I ___ TV at night.", opciones = listOf("watches", "watch", "watching", "watched"), respuesta_correcta = "watch"),
    Question(id_pregunta = 62, enunciado = "___ (estudiar).", opciones = listOf("Play", "Study", "Run", "Walk"), respuesta_correcta = "Study"),
    Question(id_pregunta = 63, enunciado = "They ___ pizza for dinner.", opciones = listOf("eats", "eating", "eat", "are eat"), respuesta_correcta = "eat"),
    Question(id_pregunta = 64, enunciado = "¿Como se dice \"Ella lee\"?", opciones = listOf("She read", "She reads", "He reads", "They read"), respuesta_correcta = "She reads"),
    Question(id_pregunta = 65, enunciado = "He ___ to the gym.", opciones = listOf("go", "goes", "going", "went"), respuesta_correcta = "goes"),
    Question(id_pregunta = 66, enunciado = "Traduce \"El ve television\".", opciones = listOf("She watches TV", "He watch TV", "He watches TV", "They watch TV"), respuesta_correcta = "He watches TV"),
    Question(id_pregunta = 67, enunciado = "My dog ___ a lot.", opciones = listOf("run", "running", "runs", "is run"), respuesta_correcta = "runs"),
    Question(id_pregunta = 68, enunciado = "She ___ a letter.", opciones = listOf("writes", "write", "writing", "wrote"), respuesta_correcta = "writes"),
    Question(id_pregunta = 69, enunciado = "It ___ a simple life.", opciones = listOf("live", "lives", "living", "is live"), respuesta_correcta = "lives"),
    Question(id_pregunta = 70, enunciado = "¿Cómo se dice \"Ella cocina\"?", opciones = listOf("She eats", "She cooking", "She cooks", "He cooks"), respuesta_correcta = "She cooks"),
    Question(id_pregunta = 71, enunciado = "He ___ breakfast.", opciones = listOf("eat", "eats", "eating", "is eat"), respuesta_correcta = "eats"),
    Question(id_pregunta = 72, enunciado = "The clock ___ fast.", opciones = listOf("tick", "ticks", "ticking", "is tick"), respuesta_correcta = "ticks"),
    Question(id_pregunta = 73, enunciado = "¿Cómo se dice \"Debajo de\"?", opciones = listOf("On", "In", "Under", "Next to"), respuesta_correcta = "Under"),
    Question(id_pregunta = 74, enunciado = "Traduce \"Al lado de\"", opciones = listOf("On", "Under", "In", "Next to"), respuesta_correcta = "Next to"),
    Question(id_pregunta = 75, enunciado = "The keys are ___ my pocket.", opciones = listOf("on", "under", "in", "next to"), respuesta_correcta = "in"),
    Question(id_pregunta = 76, enunciado = "The sofa is ___ the door.", opciones = listOf("in", "on", "under", "next to"), respuesta_correcta = "next to"),
    Question(id_pregunta = 77, enunciado = "¿Como se dice \"Cocina\"?", opciones = listOf("Bathroom", "Bedroom", "Kitchen", "Living room"), respuesta_correcta = "Kitchen"),
    Question(id_pregunta = 78, enunciado = "The picture is ___ the wall.", opciones = listOf("under", "in", "on", "next to"), respuesta_correcta = "on"),
    Question(id_pregunta = 79, enunciado = "The lamp is ___ the bed.", opciones = listOf("in", "next to", "under", "on"), respuesta_correcta = "next to"),
    Question(id_pregunta = 80, enunciado = "¿Que significa \"Upstairs\"?", opciones = listOf("Abajo", "Afuera", "Arriba", "Dentro"), respuesta_correcta = "Arriba"),
    Question(id_pregunta = 81, enunciado = "¿Como se dice \"Poder\"? (de habilidad)", opciones = listOf("Go", "Do", "Can", "Have"), respuesta_correcta = "Can"),
    Question(id_pregunta = 82, enunciado = "I ___ speak English.", opciones = listOf("am", "is", "can", "do"), respuesta_correcta = "can"),
    Question(id_pregunta = 83, enunciado = "¿Como se dice \"Nadar\"?.", opciones = listOf("Fly", "Sing", "Cook", "Swim"), respuesta_correcta = "Swim"),
    Question(id_pregunta = 84, enunciado = "We ___ fly without wings.", opciones = listOf("can´t", "can", "doesn´t", "isn´t"), respuesta_correcta = "can´t"),
    Question(id_pregunta = 85, enunciado = "Traduce \"Ellos pueden ayudarme\".", opciones = listOf("They helps me", "They can help me", "We can help me", "They help me"), respuesta_correcta = "They can help me"),
    Question(id_pregunta = 86, enunciado = "___ she cook dinner?", opciones = listOf("Does", "Is", "Can", "Has"), respuesta_correcta = "Can"),
    Question(id_pregunta = 87, enunciado = "¿Como se dice \"Si puedo\"?", opciones = listOf("No, I can´t", "Yes, I am", "Yes, I can", "Yes, I do"), respuesta_correcta = "Yes, I can"),
    Question(id_pregunta = 88, enunciado = "My sister ___ sing very well.", opciones = listOf("can", "is", "are", "do"), respuesta_correcta = "can"),
    Question(id_pregunta = 89, enunciado = "¿Como se dice \"Pan\"?", opciones = listOf("Egg", "Milk", "Bread", "Water"), respuesta_correcta = "Bread"),
    Question(id_pregunta = 90, enunciado = "Traduce \"¿Hay algo de agua?\"", opciones = listOf("Are there any water?", "Is there any water?", "There is some water?", "Do you have water?"), respuesta_correcta = "Is there any water?"),
    Question(id_pregunta = 91, enunciado = "¿Como se dice \"Queso\"?", opciones = listOf("Rice", "Tomato", "Juice", "Cheese"), respuesta_correcta = "Cheese"),
    Question(id_pregunta = 92, enunciado = "Seleccione un sustantivo contable:", opciones = listOf("Water", "Sugar", "Chairs", "Rice"), respuesta_correcta = "Chairs"),
    Question(id_pregunta = 93, enunciado = "Do you want ___ tea (pregunta de oferta)?", opciones = listOf("any", "some", "a", "an"), respuesta_correcta = "some"),
    Question(id_pregunta = 94, enunciado = "¿Que significa \"Vegetables\"?", opciones = listOf("Carne", "Frutas", "Verduras", "Lacteos"), respuesta_correcta = "Verduras"),
    Question(id_pregunta = 95, enunciado = "___ is my dog (de ella).", opciones = listOf("His", "My", "Her", "Their"), respuesta_correcta = "Her"),
    Question(id_pregunta = 96, enunciado = "Traduce \"¿Puedes ayudarme?\"", opciones = listOf("Do you help me?", "Can you help me?", "Are you help me?", "You can help me?"), respuesta_correcta = "Can you help me?"),
    Question(id_pregunta = 97, enunciado = "She ___ a doctor.", opciones = listOf("are", "am", "is", "not"), respuesta_correcta = "is"),
    Question(id_pregunta = 98, enunciado = "___ (dos).", opciones = listOf("One", "Three", "Two", "Five"), respuesta_correcta = "Two"),
    Question(id_pregunta = 99, enunciado = "I ___ some money (negativo).", opciones = listOf("don´t have any", "doesn´t have some", "don´t have some", "can´t have army"), respuesta_correcta = "don´t have any"),
    Question(id_pregunta = 100, enunciado = "___ is she (Pregunta)?", opciones = listOf("Where", "What", "Who", "When"), respuesta_correcta = "Who")
)